export enum ListingColor {
  BLACK = 'black',
  WHITE = 'white',
  GREY = 'grey',
  BLUE = 'blue',
  RED = 'red',
  GREEN = 'green',
  YELLOW = 'yellow',
  ORANGE = 'orange',
  PINK = 'pink',
  PURPLE = 'purple',
  BROWN = 'brown',
  BEIGE = 'beige',
  GOLD = 'gold',
  SILVER = 'silver',
  MULTICOLOR = 'multicolor',
  OTHER = 'other',
}
